# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meroku < Formula
  desc "Easy infrastructure management"
  homepage "https://madappgang.com"
  version "3.2.0"
  license "MIT"

  depends_on "awscli" => :optional
  depends_on "opentofu" => :optional
  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.2.0/meroku_Darwin_x86_64.tar.gz"
      sha256 "f08724669c2791154556d8a94277145bf9597ebdf9c7b0afd6d39b497cd040ae"

      def install
        bin.install "meroku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.2.0/meroku_Darwin_arm64.tar.gz"
      sha256 "9d83c5a690262cf700fc995b0fb73ed820fa0669912d1741c9297a9cb4ce2069"

      def install
        bin.install "meroku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.2.0/meroku_Linux_x86_64.tar.gz"
      sha256 "14afeb48fe49cfd8d3759c3173e0013cca3edbcc5af61661008253409748df8f"
      def install
        bin.install "meroku"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.2.0/meroku_Linux_arm64.tar.gz"
      sha256 "55a42c422defc8bd6f8bdcbd832e99e4fad024f9193beefecd05d46bb778e049"
      def install
        bin.install "meroku"
      end
    end
  end
end
