# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meroku < Formula
  desc "Easy infrastructure management"
  homepage "https://madappgang.com"
  version "1.4.4"
  license "MIT"

  depends_on "awscli" => :optional
  depends_on "opentofu" => :optional
  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v1.4.4/meroku_Darwin_x86_64.tar.gz"
      sha256 "628b248fe1a2160903bdbe654356684903866231e539f160e8e215c73c574828"

      def install
        bin.install "meroku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v1.4.4/meroku_Darwin_arm64.tar.gz"
      sha256 "162461ff235a3e72ca9924a1a39891b73c814c5cc8ab3ea1a96b0d92ea1dc794"

      def install
        bin.install "meroku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MadAppGang/infrastructure/releases/download/v1.4.4/meroku_Linux_x86_64.tar.gz"
        sha256 "705b513c38a1111a418c091cc4e05fa84a1be15dc35869d7511a60e728dd258f"

        def install
          bin.install "meroku"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MadAppGang/infrastructure/releases/download/v1.4.4/meroku_Linux_arm64.tar.gz"
        sha256 "364088e5b5aaf28b076d1c68e8d92232837659b97d90ca21f270205f781fc795"

        def install
          bin.install "meroku"
        end
      end
    end
  end
end
