# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meroku < Formula
  desc "Easy infrastructure management"
  homepage "https://madappgang.com"
  version "3.1.9"
  license "MIT"

  depends_on "awscli" => :optional
  depends_on "opentofu" => :optional
  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.1.9/meroku_Darwin_x86_64.tar.gz"
      sha256 "42c9de4b899d4142b1f75d61491f8a78f7b6fc6ef6f530dbf148e11d6ef03288"

      def install
        bin.install "meroku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.1.9/meroku_Darwin_arm64.tar.gz"
      sha256 "d2f91cec6a753d2a8d2b3869a3c5644649197ef5f4dbcc4828519c7c9b2b281a"

      def install
        bin.install "meroku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.1.9/meroku_Linux_x86_64.tar.gz"
      sha256 "57ea0d6c1617a17cb51cab36100831d761b6871ba5d174f492f2c8dbf4234eec"
      def install
        bin.install "meroku"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.1.9/meroku_Linux_arm64.tar.gz"
      sha256 "763a7eebdfaa7efcda85c89d5c62d63201957d7bdae8640b64530890906a5bc7"
      def install
        bin.install "meroku"
      end
    end
  end
end
