# This file was generated by GoReleaser. DO NOT EDIT.
cask "meroku" do
  desc "Easy infrastructure management"
  homepage "https://madappgang.com"
  version "3.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meroku"

  on_macos do
    on_intel do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.5.2/meroku_Darwin_x86_64.tar.gz"
      sha256 "3c5f634c555e9cd438390ce63ac0b75286eaaf15770fd91bb084c95fa287285f"
    end
    on_arm do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.5.2/meroku_Darwin_arm64.tar.gz"
      sha256 "19b149f1548d4205ab895d1e384ea377778f981465c5ca3fc837622b2d19d280"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.5.2/meroku_Linux_x86_64.tar.gz"
      sha256 "180eba3132eadd99861eec7c400d644415804c72eb8f2decc55071d1deee5c30"
    end
    on_arm do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.5.2/meroku_Linux_arm64.tar.gz"
      sha256 "12e525a04a8bdf0e911dc36f4cfa64f048e408edf7f2814ecec72fd182b308c2"
    end
  end

  conflicts_with formula: [
      "meroku",
    ]

  # No zap stanza required
end
