# This file was generated by GoReleaser. DO NOT EDIT.
cask "meroku" do
  desc "Easy infrastructure management"
  homepage "https://madappgang.com"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meroku"

  on_macos do
    on_intel do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v0.2.1/meroku_Darwin_x86_64.tar.gz"
      sha256 "77b51cdf5cf0a2aa602e11071bfeb900347c59ad5b6de72f02c3b4063449dcc4"
    end
    on_arm do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v0.2.1/meroku_Darwin_arm64.tar.gz"
      sha256 "51d5b4a26fea7425420bc78053a756ff487bc154369d2799cabec84240c24dd8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v0.2.1/meroku_Linux_x86_64.tar.gz"
      sha256 "604dd2ee3c60b4bb641ff08d3efdd668edb32ecaa4efb804459edb63f19c2b86"
    end
    on_arm do
      url "https://github.com/MadAppGang/infrastructure/releases/download/v0.2.1/meroku_Linux_arm64.tar.gz"
      sha256 "2829263cb5832da4ab484c41a2f8b5f226cf0e9eec526cd94a15e590b86aafe9"
    end
  end

  conflicts_with formula: [
      "meroku",
    ]

  # No zap stanza required
end
