# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meroku < Formula
  desc "Easy infrastructure management"
  homepage "https://madappgang.com"
  version "3.20.2"
  license "MIT"

  depends_on "opentofu" => :optional
  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/meroku/releases/download/v3.20.2/meroku_Darwin_x86_64.tar.gz"
      sha256 "d38bc9a09b4b1cf24026818e38d939a66afdafdd7e655602fb1ef53aff122cbd"

      def install
        bin.install "meroku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/meroku/releases/download/v3.20.2/meroku_Darwin_arm64.tar.gz"
      sha256 "f05b0960c67db49b64d9d370cc2934b73371a4e4f8e56b45dc020a1f349a1991"

      def install
        bin.install "meroku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/meroku/releases/download/v3.20.2/meroku_Linux_x86_64.tar.gz"
      sha256 "deecac5ca9324c2565e4fb5047b3398a42d4d19ae1d36216e3d6457e2571d8b6"
      def install
        bin.install "meroku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/meroku/releases/download/v3.20.2/meroku_Linux_arm64.tar.gz"
      sha256 "7870ec38e1fb5eb7461a521fbca26379e6d27cbec841aa9b79c1c8318d9ef880"
      def install
        bin.install "meroku"
      end
    end
  end

  test do
    system "#{bin}/meroku", "--version"
  end
end
