# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meroku < Formula
  desc "Easy infrastructure management"
  homepage "https://madappgang.com"
  version "3.18.5"
  license "MIT"

  depends_on "opentofu" => :optional
  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.18.5/meroku_Darwin_x86_64.tar.gz"
      sha256 "377c7015cc56111b39f17ef6ae76a3d83c04a5153aa608c84a90178517c1343b"

      def install
        bin.install "meroku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.18.5/meroku_Darwin_arm64.tar.gz"
      sha256 "357f546663699f02f5d0677adca3f95080ace300801118ac8f841ae7bc0b476e"

      def install
        bin.install "meroku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.18.5/meroku_Linux_x86_64.tar.gz"
      sha256 "8980df55214505598030e56dfb84797c99cd795722accdc77883de8a9bb2f41e"
      def install
        bin.install "meroku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MadAppGang/infrastructure/releases/download/v3.18.5/meroku_Linux_arm64.tar.gz"
      sha256 "6c898eff6b371173f6a983992130c79feb9bdb8ecbb965531ac213bbe3264779"
      def install
        bin.install "meroku"
      end
    end
  end

  test do
    system "#{bin}/meroku", "--version"
  end
end
